TycheSoftwares/custom-order-statuses-woocommerce

custom-order-statuses-woocommerce/custom-order-statuses-for-woocommerce.php
custom-order-statuses-woocommerce/includes/class-alg-wc-custom-order-statuses-core.php
custom-order-statuses-woocommerce/includes/class-alg-wc-custom-order-statuses-tool.php
custom-order-statuses-woocommerce/includes/settings/class-alg-wc-custom-order-statuses-settings-emails.php

Fixes 1.4.7

---

custom-order-statuses-woocommerce/uninstall.php

Adding the uninstall file

---

custom-order-statuses-woocommerce/custom-order-statuses-for-woocommerce.php
custom-order-statuses-woocommerce/includes/settings/class-alg-wc-custom-order-statuses-settings-emails.php
custom-order-statuses-woocommerce/includes/settings/class-alg-wc-custom-order-statuses-settings-general.php

Added utm tags to all upgrade to pro links on settings page and the 'Unlock All' link as well.

Add UTM tags to all upgrade links

---

custom-order-statuses-woocommerce/includes/class-alg-wc-custom-order-statuses-tool.php

Fixed a warning

---

custom-order-statuses-woocommerce/includes/class-alg-wc-custom-order-statuses-tool.php

Escape output

---

custom-order-statuses-woocommerce/custom-order-statuses-for-woocommerce.php
custom-order-statuses-woocommerce/readme.txt

1. Updated the version number.
2. Updated the changelog.
3. Updated WP & WC tested up to values.

Update version number

---

custom-order-statuses-woocommerce/readme.txt

Updating readme file with free & pro plugin links.

Updating readme file

---

custom-order-statuses-woocommerce/custom-order-statuses-for-woocommerce.php
custom-order-statuses-woocommerce/readme.txt

Updated the files to indicate compatibility with WC 4.0.0

Version 1.4.9

---

custom-order-statuses-woocommerce/readme.txt

Updating Git with the changes present on wp.org

Updating Git with the changes present on wp.org

---

custom-order-statuses-woocommerce/includes/class-alg-wc-custom-order-statuses-core.php

All Products page was unable to edit when our plugin was active.This is fixed now.

All Products page was unable to edit when our plugin was active.

---

custom-order-statuses-woocommerce/includes/class-alg-wc-custom-order-statuses-core.php

In this commit, I have fixed mail issue sent to admin and users when our plugin is active.
Fix #25

Fix issue#25

---

custom-order-statuses-woocommerce/readme.txt

Updated readme.txt file for WP5.5 compatibility

Updated readme.txt file for WP5.5 compatibility

---

class-alg-wc-custom-order-statuses.php
includes/class-alg-wc-custom-order-statuses-core.php
includes/class-alg-wc-custom-order-statuses-tool.php
includes/class-alg-wc-custom-post-type-for-order-statuses.php
includes/settings/class-alg-wc-custom-order-statuses-settings-emails.php

Global Level email & Migrating custom statuses into CPT

Global Level email & Migrating custom statuses into CPT

---

custom-order-statuses-for-woocommerce.php
readme.txt

Changes for v2.0.0

---

includes/settings/class-alg-wc-custom-order-statuses-settings-general.php

In this issue, I have fixed the error showing on clicking on link from the settings page. Fix #44

Fixed issue #44

---

class-alg-wc-custom-order-statuses.php
includes/class-alg-wc-custom-order-statuses-core.php
includes/settings/class-alg-wc-custom-order-statuses-settings-general.php

In this commit, I have fixed to not showing icons after added CPT. Fix #37

Fixed issue #37

---

includes/alg-wc-custom-order-statuses-functions.php
includes/class-alg-wc-custom-post-type-for-order-statuses.php

In this commit, I have added a custom slug with the 17 characters limit. Fix #45

Fixed issue #45

---

includes/class-alg-wc-custom-order-statuses-core.php

In this commit, I have fixed the issue of not applying color to the status in the order page of admin. Fix #49

Fixed issue #49

---

uninstall.php

In this commit, I have fixed the issue of deleting orders with custom statuses when deleting the plugin. Fix #21

Fixed issue #21

---

custom-order-statuses-for-woocommerce.php
readme.txt

In this commit, I have changed the version number and prepared a copy for the update.

Version 2.0.1

---

includes/class-alg-wc-custom-post-type-for-order-statuses.php

Added notice to enable colors for custom status

---

class-alg-wc-custom-order-statuses.php
includes/class-tyche-plugin-deactivation.php
includes/js/tyche.js

Updated deactivation files here.
[do-not-scan]

Fixed deactivation files.

---

class-alg-wc-custom-order-statuses.php
custom-order-statuses-for-woocommerce.php
includes/component/plugin-tracking/class-tyche-plugin-tracking.php
readme.txt

Fix #v-2.4.1 version change PR and Dismissing Notices - Implementing nonce check as well as permission/role based on this security report: [This Patchstack report](https://patchstack.com/database/report-preview/e6c07109-98f5-4411-aee3-d20efed950b7?pin=dFV4Lbv3vSS842t0)
Added the user to be logged in and permission check and nonce before the action can be executed.

Fix-#v-2.4.1

---

class-alg-wc-custom-order-statuses.php
includes/component/plugin-tracking/class-tyche-plugin-tracking.php

Changed 'ts_tracker_data' filter name

Fixed Tracking changes

---

includes/alg-wc-custom-order-statuses-functions.php

Fix #116 Compatibility with ActiveMember360

Fix #116 Compatibility with ActiveMember360

---

class-alg-wc-custom-order-statuses.php
includes/component/plugin-deactivation/class-tyche-plugin-deactivation.php
includes/js/tyche.js

Fix deactivation changes

---

includes/component/plugin-deactivation/assets/css/style.css
includes/component/plugin-deactivation/class-tyche-plugin-deactivation.php
langs/custom-order-statuses-woocommerce.po
langs/custom-order-statuses-woocommerce.pot
readme.txt

Added deactivation reason to plugin file and updated readme file, also update mo,po file
https://support.tychesoftwares.com/conversation/4994?folder_id=3

Added deactivation reason to plugin file and updated readme file

---

class-alg-wc-custom-order-statuses.php
custom-order-statuses-for-woocommerce.php
readme.txt

changelog and readme update

---

class-alg-wc-custom-order-statuses.php

Fix #122 Added plugin textdomain to inti hook

Fix #122 Added plugin textdomain to inti hook

---

includes/settings/class-alg-wc-custom-order-statuses-settings-advanced.php
includes/settings/class-alg-wc-custom-order-statuses-settings-emails.php
includes/settings/class-alg-wc-custom-order-statuses-settings-general.php

Fix #122 translation not working

Fix #122 translation not working

---

changelog.txt
class-alg-wc-custom-order-statuses.php
includes/alg-wc-custom-order-statuses-functions.php
includes/class-alg-wc-custom-order-statuses-core.php
includes/class-alg-wc-custom-order-statuses-tool.php
includes/class-alg-wc-custom-post-type-for-order-statuses.php
includes/class-cos-tracking-functions.php
includes/settings/class-alg-wc-custom-order-statuses-settings-advanced.php
includes/settings/class-alg-wc-custom-order-statuses-settings-emails.php
includes/settings/class-alg-wc-custom-order-statuses-settings-general.php
includes/settings/class-alg-wc-custom-order-statuses-settings-section.php
includes/settings/class-alg-wc-settings-custom-order-statuses.php

Phpcs fix for woo-market

---

includes/class-alg-wc-custom-post-type-for-order-statuses.php

Fix #128 fix php warrning

---

langs/custom-order-statuses-woocommerce.pot

Fix #132 Translate Plugin Name and Description in Plugin List.

Fix #132 Translate Plugin Name and Description in Plugin List.

---

changelog.txt
class-alg-wc-custom-order-statuses.php
custom-order-statuses-for-woocommerce.php
readme.txt

version change PR 2.7.0

---

includes/class-alg-wc-custom-post-type-for-order-statuses.php

Fix #136 PHP message: PHP Warning: Undefined array key "status_slug".

Fix #136 PHP message: PHP Warning: Undefined array key "status_slug".

---

includes/settings/class-alg-wc-settings-custom-order-statuses.php

Fix #134 set Reset Usage Tracking only for the general page.

Fix #134 set Reset Usage Tracking only for general page.
